language: elixir
elixir: '1.5.2'
otp_release: '19.0'
addons:
  postgresql: '9.5'
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script: mix coveralls.travis

